version: '3.8'

services:
  sveltekit:
    build:
      context: ./front
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./front:/app
      - sveltekit_node_modules:/app/node_modules
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development

  bun:
    build:
      context: ./front

    image: oven/bun:latest
    command: bun --watch run dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./shared:/app  # Korrekte Volumen-Einbindung

  caddy:
    image: caddy:2
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    ports:
      - 80:80
      - 443:443

  php:
    image: php:8.2-fpm
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/var/www/html
    ports:
      - "9000:9000"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: quickq_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  mysql-data:
  caddy_data:
  couchdb_data:
  shared:
  sveltekit_node_modules:
